### PR TITLE
Add-new controller for p2

### PR DESCRIPTION
**Pull request by WillyChennnn**
I have done the controller for p2
most of code copy from p1,
I only delete the SW and add the FSM, and the FSM also related to posedge of brtns_timeout

plz review my code thks

### CODE REVIEW

**Comment by yuyuranium** [comment]
Looks great! I will do simulation tomorrow ASAP.

**Review by yuyuranium — COMMENTED** [review]
The `color` signal seems to change too early?

image

To generate the waveform, you may try:
```
git checkout main
git pull
git checkout yuyuranium/feat/test-problem2
# go to /Problem2/src
verilator -cc -exe -O3 --x-assign fast --x-initial fast --noassert top.v sim_main.cpp --trace
make -j -C obj_dir -f Vtop.mk
obj_dir/Vtop
# then top.vcd will be generated
```

**Comment by WillyChennnn** [comment]
Ok, let me see

**Comment by yuyuranium** [comment]
Thanks! BTW, it may take a few seconds to run simulation and load the generated waveform into gtkwave.

**Review by yuyuranium — COMMENTED** [review]
This seems to fix the problem!

image

**Pull request closed without merging**
